version: "3"
services:
  #PHP Service
  crazygirl_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: crazygirl_api
    container_name: crazygirl_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: crazygirl_app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9001 remote_enable=1
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/conf.d/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    links:
        - crazygirl_redis
  # composer:
  #   restart: "no"
  #   image: composer
  #   command: install  --prefer-dist --ignore-platform-reqs --no-scripts
  #   volumes:
  #     - .:/app
  #Nginx Service
  crazygirl_webserver:
    image: nginx:alpine
    container_name: crazygirl_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  crazygirl_redis:
    image: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6378:6379"
    networks:
      - app-network
    environment: 
      - ALLOW_EMPTY_PASSWORD=true
    command: redis-server --appendonly yes
    extra_hosts:
      - "host.docker.internal:10.0.0.73"
      - "docker.for.mac.localhost:10.0.0.73"
#Docker Networks
networks:
  app-network:
    driver: bridge
  
